import os, time, sys

color_off="\033[0m"
bred="\033[1;31m"
bgreen="\033[1;32m"   

def main():
    os.system("clear")
    
    print("""\033[1;37m
      DO YOU WANT TO INSTALL BASIC PACKAGE
         
          [01] Yes
          [02] No
    """)
    userInput = input(str("     >>>\033[1;32m "))
    if userInput == "01" or userInput == "1" :
        pass
    elif userInput == "02" or userInput == "2" :
        sys.exit()
    else:
        print(" \033[1;31m  Wrong Value Entered !\033[1;37m")
	time.sleep(3)
        main()

    os.system("clear")
    print(bgreen + "")
    print("Updating Package")
    time.sleep(1)
    os.system("apt update -y")
    print(bgreen + "")
    print("Upgrading Package")
    time.sleep(1)
    os.system("apt upgrade -y")
    print(bgreen + "")
    print("Installing Git")
    time.sleep(1)
    os.system("apt install git -y")
    print(bgreen + "")
    print("Installing Python")
    time.sleep(1)
    os.system("apt install python -y")
    print(bgreen + "")
    print("Installing Bash")
    time.sleep(1)
    os.system("apt install bash -y")
    print(bgreen + "")
    print("Installing Python2")
    time.sleep(1)
    os.system("apt install python2 -y")
    print(bgreen + "")
    print("Installing PHP")
    time.sleep(1)
    os.system("apt install php -y")
    print(bgreen + "")
    print("Installing Wget")
    time.sleep(1)
    os.system("apt install wget -y")
    print(bgreen + "")
    print("Installing Curl")
    time.sleep(1)
    os.system("apt install curl -y")
    print(bgreen + "")
    print("Installing Figlet")
    time.sleep(1)
    os.system("apt install figlet -y")
    print(bgreen + "")
    print("Installing GoLang")
    time.sleep(1)
    os.system("apt install golang -y")
    print(bgreen + "")
    print("Installing Hydra")
    time.sleep(1)
    os.system("apt install hydra -y")
    print(bgreen + "")
    print("Installing Cmatrix")
    time.sleep(1)
    os.system("apt install cmatrix -y")
    print(bgreen + "")
    print("Installing Wireshark")
    time.sleep(1)
    os.system("apt install wireshark -y")
    print(bgreen + "")
    print("Installing Toilet")
    time.sleep(1)
    os.system("apt install toilet -y")
    print(bgreen + "")
    print("Installing cowsay")
    time.sleep(1)
    os.system("apt install cowsay -y")
    print(bgreen + "")
    print("Installing Ruby")
    time.sleep(1)
    os.system("apt install ruby -y")
    print(bgreen + "")
    print("Installing Nmap")
    time.sleep(1)
    os.system("apt install nmap -y")
    print(bgreen + "")
    print("Installing Wgetrc")
    time.sleep(1)
    os.system("apt install wgetrc -y")
    print(bgreen + "")
    print("Installing Unzip")
    time.sleep(1)
    os.system("apt install unzip -y")
    print(bgreen + "")
    print("Installing Zip")
    time.sleep(1)
    os.system("apt install zip -y")
    print(bgreen + "")
    print("Installing Apache2")
    time.sleep(1)
    os.system("apt-get install apache2 -y")
    print(bgreen + "")
    print("Installing OpenSSH")
    time.sleep(1)
    os.system("apt install openssh -y")
    print(bgreen + "")
    print("Installing Tor")
    time.sleep(1)
    os.system("apt install tor -y")
    print(bgreen + "")
    print("Installing Clang")
    time.sleep(1)
    os.system("apt install clang -y")
    print(bgreen + "")
    print("Upgrading Pip")
    time.sleep(1)
    os.system("pip install --upgrade pip")
    print(bgreen + "")
    print("Upgrading Pip2")
    time.sleep(1)
    os.system("pip2 install --upgrade pip")
    print(bgreen + "")
    print("Installing Mechanize Module")
    time.sleep(1)
    os.system("pip install mechanize")
    print(bgreen + "")
    print("Installing Requests Module")
    time.sleep(1)
    os.system("pip install requests")
    print(bgreen + "")
    print("Installing Bs4 Module")
    time.sleep(1)
    os.system("pip install bs4")
    print(bgreen + "")
    print("Installing SMTPlib Module")
    time.sleep(1)
    os.system("pip install smtplib")
    print(bgreen + "")
    print("Installing Lolcat Gem")
    time.sleep(1)
    os.system("gem install lolcat")
    print(bgreen + "")
    print("Installing Requests Module For Python2")
    time.sleep(1)
    os.system("pip2 install requests")
    print(bgreen + "")
    print("Installing Mechanize Module For Python2")
    time.sleep(1)
    os.system("pip2 install mechanize")
    print(bgreen + "")
    print("Installing Bs4 Module For Python2")
    time.sleep(1)
    os.system("pip2 install bs4")
    print(bgreen+"\n ["+u'\u2713'+"] All Pkg Installed Successfully.["+u'\u2713'+"] \n\n\n"+color_off)
    time.sleep(2)

if __name__ == "__main__" :
    main()
